In [213]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [133]:
# Total amount of pages 50 from 1-50 --> 1000 books to scrape info

number_pages_to_scrape = 10
 
books_to_scrap_url = "http://books.toscrape.com/catalogue/category/books_1/page-1.html"
response = requests.get(books_to_scrap_url)

# All html
soup = BeautifulSoup(response.text, "html.parser")

In [138]:
bookshelf = soup.find_all('li', {'class': "col-xs-6 col-sm-4 col-md-3 col-lg-3"})

In [198]:
master_list = []

for books in bookshelf:
    data = {}
    
    print(books.h3.a['title'])
    book_title = books.h3.a['title']
    data['book_title'] = book_title
    
    print(books.find_all("p", {"class": "price_color"})[0].text.strip())
    book_price = books.find_all("p", {"class": "price_color"})[0].text
    data['book_price'] = book_price
    
    print(books.find_all("div", {"class": "image_container"})[0].a['href'].replace("../..",""))
    catalog = "https://books.toscrape.com/catalogue"
    book_url = catalog + books.find_all("div", {"class": "image_container"})[0].a['href'].replace("../..","")
    data['book_url'] = book_url
    
    print(books.p['class'][1])
    book_rating = books.p['class'][1]
    data['book_rating'] = book_rating
    
    master_list.append(data)
    
    print('-' * 50)

A Light in the Attic
Â£51.77
/a-light-in-the-attic_1000/index.html
Three
--------------------------------------------------
Tipping the Velvet
Â£53.74
/tipping-the-velvet_999/index.html
One
--------------------------------------------------
Soumission
Â£50.10
/soumission_998/index.html
One
--------------------------------------------------
Sharp Objects
Â£47.82
/sharp-objects_997/index.html
Four
--------------------------------------------------
Sapiens: A Brief History of Humankind
Â£54.23
/sapiens-a-brief-history-of-humankind_996/index.html
Five
--------------------------------------------------
The Requiem Red
Â£22.65
/the-requiem-red_995/index.html
One
--------------------------------------------------
The Dirty Little Secrets of Getting Your Dream Job
Â£33.34
/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
Four
--------------------------------------------------
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Â£17.93
/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
Three
--------------------------------------------------
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Â£22.60
/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
Four
--------------------------------------------------
The Black Maria
Â£52.15
/the-black-maria_991/index.html
One
--------------------------------------------------
Starving Hearts (Triangular Trade Trilogy, #1)
Â£13.99
/starving-hearts-triangular-trade-trilogy-1_990/index.html
Two
--------------------------------------------------
Shakespeare's Sonnets
Â£20.66
/shakespeares-sonnets_989/index.html
Four
--------------------------------------------------
Set Me Free
Â£17.46
/set-me-free_988/index.html
Five
--------------------------------------------------
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Â£52.29
/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
Five
--------------------------------------------------
Rip it Up and Start Again
Â£35.02
/rip-it-up-and-start-again_986/index.html
Five
--------------------------------------------------
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Â£57.25
/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
Three
--------------------------------------------------
Olio
Â£23.88
/olio_984/index.html
One
--------------------------------------------------
Mesaerion: The Best Science Fiction Stories 1800-1849
Â£37.59
/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
One
--------------------------------------------------
Libertarianism for Beginners
Â£51.33
/libertarianism-for-beginners_982/index.html
Two
--------------------------------------------------
It's Only the Himalayas
Â£45.17
/its-only-the-himalayas_981/index.html
Two
--------------------------------------------------

In [217]:
master_list = []

start_clock = time.process_time_ns()

for page in range(1, 51):
    print(f"Page {page} beginning scraping...")
    
    books_url_scrap = f"http://books.toscrape.com/catalogue/category/books_1/page-{page}.html"
    response = requests.get(books_url_scrap)
    
    soup = BeautifulSoup(response.text, "html.parser")
    
    bookshelf = soup.find_all('li', {'class': "col-xs-6 col-sm-4 col-md-3 col-lg-3"})
    
    for books in bookshelf:
        data = {}
        
        book_title = books.h3.a['title']
        data['book_title'] = book_title

        book_price = books.find_all("p", {"class": "price_color"})[0].text
        data['book_price'] = book_price

        catalog = "https://books.toscrape.com/catalogue"
        book_url = catalog + books.find_all("div", {"class": "image_container"})[0].a['href'].replace("../..","")
        data['book_url'] = book_url

        book_rating = books.p['class'][1]
        data['book_rating'] = book_rating

        master_list.append(data)
    
    print(f"Page {page} scrapped successfully!\n")
    
end_clock = time.process_time_ns()
print(f"Total Scraping time: {end_clock - start_clock} ns")

Page 1 beginning scraping...
Page 1 scrapped successfully!

Page 2 beginning scraping...
Page 2 scrapped successfully!

Page 3 beginning scraping...
Page 3 scrapped successfully!

Page 4 beginning scraping...
Page 4 scrapped successfully!

Page 5 beginning scraping...
Page 5 scrapped successfully!

Page 6 beginning scraping...
Page 6 scrapped successfully!

Page 7 beginning scraping...
Page 7 scrapped successfully!

Page 8 beginning scraping...
Page 8 scrapped successfully!

Page 9 beginning scraping...
Page 9 scrapped successfully!

Page 10 beginning scraping...
Page 10 scrapped successfully!

Page 11 beginning scraping...
Page 11 scrapped successfully!

Page 12 beginning scraping...
Page 12 scrapped successfully!

Page 13 beginning scraping...
Page 13 scrapped successfully!

Page 14 beginning scraping...
Page 14 scrapped successfully!

Page 15 beginning scraping...
Page 15 scrapped successfully!

Page 16 beginning scraping...
Page 16 scrapped successfully!

Page 17 beginning scraping...
Page 17 scrapped successfully!

Page 18 beginning scraping...
Page 18 scrapped successfully!

Page 19 beginning scraping...
Page 19 scrapped successfully!

Page 20 beginning scraping...
Page 20 scrapped successfully!

Page 21 beginning scraping...
Page 21 scrapped successfully!

Page 22 beginning scraping...
Page 22 scrapped successfully!

Page 23 beginning scraping...
Page 23 scrapped successfully!

Page 24 beginning scraping...
Page 24 scrapped successfully!

Page 25 beginning scraping...
Page 25 scrapped successfully!

Page 26 beginning scraping...
Page 26 scrapped successfully!

Page 27 beginning scraping...
Page 27 scrapped successfully!

Page 28 beginning scraping...
Page 28 scrapped successfully!

Page 29 beginning scraping...
Page 29 scrapped successfully!

Page 30 beginning scraping...
Page 30 scrapped successfully!

Page 31 beginning scraping...
Page 31 scrapped successfully!

Page 32 beginning scraping...
Page 32 scrapped successfully!

Page 33 beginning scraping...
Page 33 scrapped successfully!

Page 34 beginning scraping...
Page 34 scrapped successfully!

Page 35 beginning scraping...
Page 35 scrapped successfully!

Page 36 beginning scraping...
Page 36 scrapped successfully!

Page 37 beginning scraping...
Page 37 scrapped successfully!

Page 38 beginning scraping...
Page 38 scrapped successfully!

Page 39 beginning scraping...
Page 39 scrapped successfully!

Page 40 beginning scraping...
Page 40 scrapped successfully!

Page 41 beginning scraping...
Page 41 scrapped successfully!

Page 42 beginning scraping...
Page 42 scrapped successfully!

Page 43 beginning scraping...
Page 43 scrapped successfully!

Page 44 beginning scraping...
Page 44 scrapped successfully!

Page 45 beginning scraping...
Page 45 scrapped successfully!

Page 46 beginning scraping...
Page 46 scrapped successfully!

Page 47 beginning scraping...
Page 47 scrapped successfully!

Page 48 beginning scraping...
Page 48 scrapped successfully!

Page 49 beginning scraping...
Page 49 scrapped successfully!

Page 50 beginning scraping...
Page 50 scrapped successfully!

Total Scraping time: 2665242000 ns

In [221]:
df = pd.DataFrame(master_list)
df.tail()

,book_title,book_price,book_url,book_rating
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,https://books.toscrape.com/catalogue/alice-in-...,One
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,https://books.toscrape.com/catalogue/ajin-demi...,Four
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,https://books.toscrape.com/catalogue/a-spys-de...,Five
998,1st to Die (Women's Murder Club #1),Â£53.98,https://books.toscrape.com/catalogue/1st-to-di...,One
999,"1,000 Places to See Before You Die",Â£26.08,https://books.toscrape.com/catalogue/1000-plac...,Five

In [224]:
df['book_price'] = df['book_price'].apply(lambda x: x.strip('Â'))

In [226]:
df.tail(30)

,book_title,book_price,book_url,book_rating
970,Lord of the Flies,£24.89,https://books.toscrape.com/catalogue/lord-of-t...,Three
971,Listen to Me (Fusion #1),£58.99,https://books.toscrape.com/catalogue/listen-to...,Three
972,Kitchens of the Great Midwest,£57.20,https://books.toscrape.com/catalogue/kitchens-...,Five
973,Jane Eyre,£38.43,https://books.toscrape.com/catalogue/jane-eyre...,Five
974,Imperfect Harmony,£34.74,https://books.toscrape.com/catalogue/imperfect...,Four
975,Icing (Aces Hockey #2),£40.44,https://books.toscrape.com/catalogue/icing-ace...,Four
976,"Hawkeye, Vol. 1: My Life as a Weapon (Hawkeye #1)",£45.24,https://books.toscrape.com/catalogue/hawkeye-v...,Three
977,Having the Barbarian's Baby (Ice Planet Barbar...,£34.96,https://books.toscrape.com/catalogue/having-th...,Four
978,"Giant Days, Vol. 1 (Giant Days #1-4)",£56.76,https://books.toscrape.com/catalogue/giant-day...,Four
979,"Fruits Basket, Vol. 1 (Fruits Basket #1)",£40.28,https://books.toscrape.com/catalogue/fruits-ba...,Five
980,Frankenstein,£38.00,https://books.toscrape.com/catalogue/frankenst...,Two
981,Forever Rockers (The Rocker #12),£28.80,https://books.toscrape.com/catalogue/forever-r...,Three
982,Fighting Fate (Fighting #6),£39.24,https://books.toscrape.com/catalogue/fighting-...,Three
983,Emma,£32.93,https://books.toscrape.com/catalogue/emma_17/i...,Two
984,"Eat, Pray, Love",£51.32,https://books.toscrape.com/catalogue/eat-pray-...,Three
985,Deep Under (Walker Security #1),£47.09,https://books.toscrape.com/catalogue/deep-unde...,Five
986,Choosing Our Religion: The Spiritual Lives of ...,£28.42,https://books.toscrape.com/catalogue/choosing-...,Four
987,Charlie and the Chocolate Factory (Charlie Buc...,£22.85,https://books.toscrape.com/catalogue/charlie-a...,Three
988,Charity's Cross (Charles Towne Belles #4),£41.24,https://books.toscrape.com/catalogue/charitys-...,One
989,Bright Lines,£39.07,https://books.toscrape.com/catalogue/bright-li...,Five
990,Bridget Jones's Diary (Bridget Jones #1),£29.82,https://books.toscrape.com/catalogue/bridget-j...,One
991,Bounty (Colorado Mountain #7),£37.26,https://books.toscrape.com/catalogue/bounty-co...,Four
992,Blood Defense (Samantha Brinkman #1),£20.30,https://books.toscrape.com/catalogue/blood-def...,Three
993,"Bleach, Vol. 1: Strawberry and the Soul Reaper...",£34.65,https://books.toscrape.com/catalogue/bleach-vo...,Five
994,Beyond Good and Evil,£43.38,https://books.toscrape.com/catalogue/beyond-go...,One
995,Alice in Wonderland (Alice's Adventures in Won...,£55.53,https://books.toscrape.com/catalogue/alice-in-...,One
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",£57.06,https://books.toscrape.com/catalogue/ajin-demi...,Four
997,A Spy's Devotion (The Regency Spies of London #1),£16.97,https://books.toscrape.com/catalogue/a-spys-de...,Five
998,1st to Die (Women's Murder Club #1),£53.98,https://books.toscrape.com/catalogue/1st-to-di...,One
999,"1,000 Places to See Before You Die",£26.08,https://books.toscrape.com/catalogue/1000-plac...,Five

In [227]:
df.to_csv("books_scraping.csv")